#!/bin/bash
while(true)
do
num=`ps aux|grep taobaomonitord|grep -v grep|wc -l`
echo $num
if [ $num -lt 1 ];then
echo starting...
cd /www/taobao
nohup php taobaomonitord.php >> log/monitord.log &
else
echo running
fi
sleep 2
done
